version: "3.8"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres
    environment:
      POSTGRES_DB: recipes
      POSTGRES_USER: ir_user
      POSTGRES_PASSWORD: 1nf0Rm4t10NR3t
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: recipes
      DB_USER: ir_user
      DB_PASSWORD: 1nf0Rm4t10NR3t
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    command: ["python", "API.py"]

volumes:
  postgres_data:
